import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { DataProvider } from "./contexts/DataContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <DataProvider>
          <main>{children}</main>
        </DataProvider>
      </body>
    </html>
  );
}
